#OBJECTS =test.o

VPATH = ./src: ./obj: ./header

#vpath %.cpp src
#ALL: Praser 

Praser: lis_to_csv.cpp
	g++ -std=c++11 -o $@ $<

#test.o: test.cpp
#	g++ -std=c++11 -o test.o ./src/test.cpp

#lis_to_scv.o: lis_to_scv.cpp
#	g++ -std=c++11 -o lis_to_scv.o lis_to_scv.cpp

#clean:
#	@rm $(OBJECTS)

